### ISSUE TITLE
Couldn't find intersection babe lerror

### ISSUE THREAD

**Issue by yawhide** [davidosborn/crypto-tax-calculator#4]
Hello,

I am getting this error when I try to run `npm run build`.
![image](https://user-images.githubusercontent.com/5014112/51430133-9488d680-1be4-11e9-8410-a5901a0aa6e3.png)

I also get this error when i try to run `npm start`
![image](https://user-images.githubusercontent.com/5014112/51430139-a8343d00-1be4-11e9-97c5-d283983f3958.png)
(seems like a similar error)

any idea how to fix this? I am not very familiar with babel and how it works.

Thanks!

**Comment by davidosborn** [comment]
Please forgive the delayed response. I think this is a problem with Babel minify. I have since removed this library from the dependencies, so this error will probably no longer occur. Please let me know if it does.
